#!/bin/bash

git fetch -p

for type in 'feature' 'bugfix'; do
  # Remove remote branches
  git branch -r --merged develop | grep origin/$type 2>/dev/null | sed 's/origin\///' | xargs -I% sh -c 'git push origin :%; git branch -d %'
done

exit 0
