#!/bin/bash

pod_name=$(~/bin/get_pod_name $1)

shift

container_name=$(kubectl describe pod $pod_name | grep -A1 Containers | tail -1 | sed -e 's/://')

kubectl exec $pod_name -c $container_name -it -- $@
