#!/bin/bash

if [ -z "$1" ]; then
   arg=default
else
   arg=$1
fi

. ~/.p4_functions

p4_login_check

if [[ "$arg" =~ ^[0-9]+$ || "default" == "$arg" ]]; then
   vim_tab_max=`vim --cmd 'set tabpagemax' --cmd quit 2>/dev/null | sed '$ s/.*=\(.*\)/\1/'`
   num_files=0
   diff_files=

   if [ "shelf" == "$2" ]; then
      vim_diff_function="P4Diff(\"@=$arg\")"
      get_p4_files $arg "-Rs -Ro"
   fi
 
   if [ -z "$files" ]; then
      vim_diff_function="P4DiffCL('@=', $arg)"
      get_p4_files $arg "-Rs"
   fi

   if [ -z "$files" ]; then
      vim_diff_function="P4Diff('')"
      get_p4_files $arg "-Ro"
   fi

   if [ -z "$files" ]; then
      vim_diff_function="P4DiffCL('@', $arg)"
      get_p4_files $arg
   fi

   if [ -n "$files" ]; then
      for file in $files
      do
         num_files=$(($num_files + 1))
         diff_files="$diff_files $file"

         if [ "$vim_tab_max" -eq "$num_files" ]; then
            vim -p -c "silent tabdo call $vim_diff_function" -c "tabm 0" $diff_files
            num_files=0
            diff_files=
         fi
      done
 
      if [ "0" -lt "$num_files" ]; then
         vim -p -c "silent tabdo call $vim_diff_function" -c "tabm 0" $diff_files
      fi
   else
      echo "Cannot find files"
   fi

elif [ -e "$arg" ]; then
   vim -p -c "silent tabdo call P4Diff()" -c "tabm 0" $arg
else
   echo "No file or changelist $arg"
fi
