#!/bin/bash

if [ -z "$1" ]; then
   arg="default"
else
   arg=$1
fi

. ~/.p4_functions

p4_login_check
 
get_p4_files $arg "-Rs -Ro"
files=`echo $files | awk '{for (i=1; i <= NF; ++i) print $i"@=""'${arg}'"}'`

if [ -z "$files" ]; then
   get_p4_files $arg "-Ro"
fi

if [ -z "$files" ]; then
   files=$arg
fi

for file in $files; do
   P4DIFF= p4 diff -dU5Nwa $file
done
