#! /bin/sh
# tags default ruby and associated gems

SRC="${rvm_path}/rubies/`rvm current`"
echo "SRC: ${SRC}"

GEMS=`rvm gemdir`/gems
echo "GEMS: ${GEMS}"

DEST=tags/`rvm current`
echo "DEST: ${DEST}"
mkdir -p $(dirname $DEST)
rm $DEST

ctags \
 --exclude=.git \
 --exclude=tags \
 --exclude=logs \
 --exclude=doc \
 -R -f $DEST $SRC $GEMS
