#!/bin/bash

servers=$@
export SSHPASS=''

for serv in $servers; do
  sshpass -e ssh $serv 'mkdir -p .ssh && cat >> .ssh/authorized_keys' < ~/.ssh/id_rsa.pub
  sshpass -e ssh $serv 'chmod 700 .ssh && chmod 640 .ssh/authorized_keys'
done
