#!/bin/bash

vim_tab_max=`vim --cmd 'set tabpagemax' --cmd quit 2>/dev/null | sed '$ s/.*=\(.*\)/\1/'`

dir=$1
files=`ls $1`

if [ -n "$files" ]; then
   count=0
   num_files=0
   total=$(echo \"$files\" | wc -w)

   for file in $files; do
      count=$(( $count + 1 ))

      if [ -f "$dir/$file" ]; then
         num_files=$(($num_files + 1))
         dir_files="$dir_files $dir/$file"
      fi

      if [ "$vim_tab_max" -eq "$num_files" -o "$count" -eq "$total" ]; then
         vim -p -c "tabm 0" $dir_files
         num_files=0
         dir_files=
      fi
   done
else
   echo "Cannot find files"
fi
