#!/bin/sh

~/bin/git_hooks/ctags >/dev/null 2>&1 &

git fetch -p

for type in 'feature' 'bugfix'; do
  # Remove remote branches
  git branch -r --merged develop | grep origin/$type 2>/dev/null | sed 's/origin\///' | xargs -I% git push origin :%
done

for branch in $(git for-each-ref --format='%(refname:short):%(upstream:short)' refs/heads); do
  local=${branch%:*}
  remote=${branch#*:}

  if [ -n "$remote" ]; then
    git show-ref -q --verify refs/remotes/$remote

    if [ $? -ne 0 ]; then
      git branch -d $local
    fi
  fi
done

exit 0
